import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import { EB_Garamond } from "next/font/google";
import Footer from "./components/footer/Footer";
import QueryProvider from "@/providers/QueryProvider";

const inter = Inter({ subsets: ["latin"] });
const garamond = EB_Garamond({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Moon Store App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <QueryProvider>{children}</QueryProvider>
        <Footer />
      </body>
    </html>
  );
}
